### ISSUE TITLE
Update to support newer versions of VSfM

### ISSUE THREAD

**Issue by Lelelo1** [mrward/MonoDevelop.DotNetCoreSupportAnyTargetFrameworkAddin#2]
Update to support newer versions of VFfM:

![VSfM cant install extension](https://user-images.githubusercontent.com/42244983/61789017-e3256080-ae13-11e9-8b7c-21176deec4d0.png)

When trying to install v1.0 extension from file.

https://oren.codes/2017/08/29/use-all-tfms-with-sdk-style-projects-in-visual-studio-for-mac/
https://github.com/mrward/temp-addin-upload/raw/master/DotNetCoreSupportAnyTargetFramework/DotNetCoreSupportAnyTargetFramework.DotNetCoreSupportAnyTargetFramework_1.0.mpack

**Comment by mrward** [comment]
This is not needed in MonoDevelop 8.0. The DotNetCoreProjectExtension in MonoDevelop 8.0 does not restrict the target frameworks.
